version: 2.1

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job1
      
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job2
                   echo << pipeline.project.git_url >>
                   echo ${CIRCLE_USERNAME}
                                      
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  papu:
   jobs:
     - premier
  
  tata:
    jobs:
      - deuxieme
      
  lala:
    jobs:
      - troisieme
